// <auto-generated />
using System;
using App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Sqlite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241122210035_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("App.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("AppointmentTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColourUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("HairStyleCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode1")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("HairStyleCode");

                    b.HasIndex("ProductCode1");

                    b.HasIndex("StaffId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("App.Models.ClientEntity", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeBandCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CellPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NaturalHairColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("AgeBandCode");

                    b.HasIndex("GenderCode");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("App.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("App.Models.DocumentUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserType")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentUsers");
                });

            modelBuilder.Entity("App.Models.PaymentDetail", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfPayment")
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClientId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("App.Models.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("App.Models.RefAgeBand", b =>
                {
                    b.Property<string>("AgeBandCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeBandDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("AgeBandCode");

                    b.ToTable("AgeBands");
                });

            modelBuilder.Entity("App.Models.RefGender", b =>
                {
                    b.Property<string>("GenderCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("GenderCode");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("App.Models.RefHairStyle", b =>
                {
                    b.Property<string>("HairStyleCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HairStyleDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("HairStyleCode");

                    b.ToTable("HairStyles");
                });

            modelBuilder.Entity("App.Models.RefSalonTreatment", b =>
                {
                    b.Property<string>("SalonTreatmentCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StandardPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("TreatmentDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("SalonTreatmentCode");

                    b.ToTable("SalonTreatments");
                });

            modelBuilder.Entity("App.Models.RefStaffJobTitle", b =>
                {
                    b.Property<string>("JobCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("JobCode");

                    b.ToTable("StaffJobTitles");
                });

            modelBuilder.Entity("App.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateJoined")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLeft")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitleJobCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffName")
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId");

                    b.HasIndex("JobTitleJobCode");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("App.Models.StaffCharge", b =>
                {
                    b.Property<string>("JobCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChargeAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitleJobCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalonTreatmentCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalonTreatmentCode1")
                        .HasColumnType("TEXT");

                    b.HasKey("JobCode");

                    b.HasIndex("JobTitleJobCode");

                    b.HasIndex("SalonTreatmentCode1");

                    b.ToTable("StaffCharges");
                });

            modelBuilder.Entity("App.Models.Appointment", b =>
                {
                    b.HasOne("App.Models.ClientEntity", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId");

                    b.HasOne("App.Models.RefHairStyle", "HairStyle")
                        .WithMany("Appointments")
                        .HasForeignKey("HairStyleCode");

                    b.HasOne("App.Models.Product", "Product")
                        .WithMany("Appointments")
                        .HasForeignKey("ProductCode1");

                    b.HasOne("App.Models.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId");

                    b.Navigation("Client");

                    b.Navigation("HairStyle");

                    b.Navigation("Product");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("App.Models.ClientEntity", b =>
                {
                    b.HasOne("App.Models.RefAgeBand", "AgeBand")
                        .WithMany("Clients")
                        .HasForeignKey("AgeBandCode");

                    b.HasOne("App.Models.RefGender", "Gender")
                        .WithMany("Clients")
                        .HasForeignKey("GenderCode");

                    b.Navigation("AgeBand");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("App.Models.DocumentUser", b =>
                {
                    b.HasOne("App.Models.Document", "Document")
                        .WithMany("DocumentUsers")
                        .HasForeignKey("DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("App.Models.PaymentDetail", b =>
                {
                    b.HasOne("App.Models.ClientEntity", "Client")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("App.Models.Staff", b =>
                {
                    b.HasOne("App.Models.RefStaffJobTitle", "JobTitle")
                        .WithMany("Staff")
                        .HasForeignKey("JobTitleJobCode");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("App.Models.StaffCharge", b =>
                {
                    b.HasOne("App.Models.RefStaffJobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleJobCode");

                    b.HasOne("App.Models.RefSalonTreatment", "SalonTreatment")
                        .WithMany("StaffCharges")
                        .HasForeignKey("SalonTreatmentCode1");

                    b.Navigation("JobTitle");

                    b.Navigation("SalonTreatment");
                });

            modelBuilder.Entity("App.Models.ClientEntity", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("App.Models.Document", b =>
                {
                    b.Navigation("DocumentUsers");
                });

            modelBuilder.Entity("App.Models.Product", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("App.Models.RefAgeBand", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("App.Models.RefGender", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("App.Models.RefHairStyle", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("App.Models.RefSalonTreatment", b =>
                {
                    b.Navigation("StaffCharges");
                });

            modelBuilder.Entity("App.Models.RefStaffJobTitle", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("App.Models.Staff", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
